#!/usr/bin/python
import numpy as np
import matplotlib.pylab as pl

#Need to go back and organize labeling/commenting
#load data from files
data1  = np.loadtxt('sn2011fe-visit3-hst.flm')
data2  = np.loadtxt('sn2011by-hst+lick.flm')

#find the overlapping region of X (wavelength values)
for i in range(len(data2[:,0])):
	if data2[:,0][i]==data1[:,0][0]:
		start = i

stop = start+len(data1[:,0])

#Truncate data2 and label it as newdata2
newdata2_X = []
newdata2_Y = []
newdata2_X = data2[:,0][start:stop] 
newdata2_Y = data2[:,1][start:stop]

data1_X = []
data1_Y = []

data1_X = data1[:,0]
#print data1_X 
data1_Y = data1[:,1]

#Calculate the average of the spectra
#Spectra has not been redshifted or the flux adjusted, this needs to be done.
avg_wave = np.divide(np.add(data1_X,newdata2_X),2)
avg_flux = np.divide(np.add(data1_Y,newdata2_Y),2)

#Some bugs in wrting avg values to file, will fix
"""
datafile = open('testdata.txt','w')

for i in range(len(avg_wave)):
	row = str(avg_wave[i] + '\t' + str(avg_flux[i] + '\n'
	datafile.write('row')
datafile.close()
"""
plot1,  = pl.plot(data1_X,data1_Y,'m')
plot2,  = pl.plot(newdata2_X,newdata2_Y,'r')
plot3,  = pl.plot(avg_wave,avg_flux,'k')

pl.title('Comparison of Spectra')
pl.xlabel('Wavelength (??)')
pl.ylabel('Flux (??)')

pl.legend([plot1,plot2,plot3],('SN2011fe','SN2011by','Average Flux'),'upper right',numpoints=1)
#pl.savefig('Spectra.png')
pl.show()






